# Generated by Django 3.1.3 on 2021-02-24 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0002_courseoffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffered',
            name='course_chapter',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
