# Generated by Django 3.1.3 on 2021-02-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0003_courseoffered_course_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffered',
            name='course_duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
