# Generated by Django 3.1.3 on 2021-02-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0004_courseoffered_course_duration'),
        ('MaxproApp', '0003_auto_20210224_2128'),
    ]

    operations = [
    ]
