# Generated by Django 3.1.3 on 2021-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0005_merge_20210225_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_image',
            field=models.ImageField(default='', upload_to='images/about'),
        ),
        migrations.AlterField(
            model_name='courseoffered',
            name='course_image',
            field=models.ImageField(default='', upload_to='images/courses'),
        ),
    ]
