# Generated by Django 3.1.3 on 2021-04-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0007_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_at',
            new_name='gallery_cat',
        ),
    ]
