# Generated by Django 3.1.7 on 2021-04-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0008_auto_20210421_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
