# Generated by Django 3.1.3 on 2021-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0008_auto_20210421_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='', max_length=50)),
                ('course_desc', models.TextField()),
                ('course_icon', models.ImageField(default='', upload_to='images/premiumcoursesicon')),
            ],
        ),
    ]
