# Generated by Django 3.1.7 on 2021-04-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0009_auto_20210424_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
