# Generated by Django 3.1.7 on 2021-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0010_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('gender', models.CharField(choices=[('select', 'SELECT'), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='select', max_length=20)),
                ('street', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('course', models.ManyToManyField(to='MaxproApp.CourseOffered')),
            ],
        ),
    ]
