# Generated by Django 3.1.7 on 2021-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0011_studentregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
    ]
