# Generated by Django 3.1.7 on 2021-04-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0012_auto_20210425_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='date',
            new_name='birthdate',
        ),
    ]
