# Generated by Django 3.1.7 on 2021-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0013_auto_20210430_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='course',
            field=models.ManyToManyField(null=True, to='MaxproApp.CourseOffered'),
        ),
    ]
