# Generated by Django 3.1.7 on 2021-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0015_remove_studentregister_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='course',
            field=models.ManyToManyField(to='MaxproApp.CourseOffered'),
        ),
    ]
