# Generated by Django 3.1.7 on 2021-04-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0016_auto_20210430_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='course',
        ),
        migrations.AddField(
            model_name='studentregister',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MaxproApp.courseoffered'),
            preserve_default=False,
        ),
    ]
