# Generated by Django 3.1.7 on 2021-04-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0017_auto_20210430_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='course',
            new_name='course_id',
        ),
    ]
