# Generated by Django 3.1.7 on 2021-04-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0018_auto_20210430_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='course_id',
            new_name='course',
        ),
    ]
