# Generated by Django 3.1.7 on 2021-04-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0019_auto_20210430_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='gender',
            field=models.CharField(choices=[('select', 'SELECT'), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=20),
        ),
    ]
