# Generated by Django 3.1.7 on 2021-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0020_auto_20210430_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
