# Generated by Django 3.1.7 on 2021-05-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0009_premiumcourses'),
        ('MaxproApp', '0021_auto_20210430_1854'),
    ]

    operations = [
    ]
