# Generated by Django 3.1.3 on 2021-05-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0021_auto_20210430_1854'),
        ('MaxproApp', '0009_premiumcourses'),
    ]

    operations = [
    ]
