# Generated by Django 3.1.7 on 2021-05-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0022_merge_20210502_0959'),
        ('MaxproApp', '0022_merge_20210501_1542'),
    ]

    operations = [
    ]
