# Generated by Django 3.1.7 on 2021-05-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0024_courseenroll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremiumCourses',
            new_name='PremiumCourse',
        ),
        migrations.RenameModel(
            old_name='CourseEnroll',
            new_name='PremiumCourseEnroll',
        ),
    ]
