# Generated by Django 3.1.7 on 2021-05-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0025_auto_20210506_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcourseenroll',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='premiumcourseenroll',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='premiumcourseenroll',
            name='precourse_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MaxproApp.premiumcourse'),
            preserve_default=False,
        ),
    ]
