# Generated by Django 3.1.7 on 2021-05-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaxproApp', '0026_auto_20210508_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumcourseenroll',
            old_name='precourse_id',
            new_name='premium_course',
        ),
        migrations.AlterField(
            model_name='premiumcourseenroll',
            name='gender',
            field=models.CharField(choices=[('select', 'SELECT'), ('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], default='Select', max_length=20),
        ),
    ]
